apps:
    0:
        enabled: true
        packet: evaluation/scion_2seg_1500byte.bin
        pktgen_port:           384
        timer_nanosec:           0
        batch_count:         10000
        packets_per_batch:   10000
        ibg:                     0
        ibg_jitter:              0
        ipg:                     0
        ipg_jitter:              0
        eg_port_group:           0

eg_port_groups:
    0: [392]
